server:
    port: 9010
    maxHttpHeaderSize: 10240
    servlet:
        context-path: /wcProgram-request
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/sys?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: p@ssw0rd
    redis:
        host: localhost
        port: 6379
        #  password: yourpassword  # 本地redis暂无密码
    kafka:
        bootstrap-servers: localhost:9091  # Kafka 服务器地址
        template:
            default-topic: demo              # 默认主题
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer  # 键的序列化器
            value-serializer: org.apache.kafka.common.serialization.StringSerializer  # 值的序列化器
            acks: -1  # 确认机制，-1 表示所有副本都确认后才返回
            retries: 3  # 发送失败后的重试次数
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # 键的反序列化器
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # 值的反序列化器
            group-id: test-consumer-group  # 消费者组
            auto-offset-reset: latest  # 偏移量重置策略，latest 表示从最新的消息开始消费
    #    main:
#        allow-bean-definition-overriding: true
    application:
        name: wChartProgram
    profiles:
        active: ${package.environment}
    servlet:
        multipart:
            maxFileSize: 512MB
            maxRequestSize: 300MB
    mvc:
        async:
            request-timeout: 60000
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml

logging:
    level:
        root: INFO
        org.springframework: DEBUG

## 白名单配置，springboot启动时会忽略，不进行身份认证和授权校验
secure:
    ignored:
        urls:
            - /swagger-ui.html
            - /swagger-ui/**
            - /swagger-resources/**
            - /swagger/**
            - /v3/**
            - /**/*.js
            - /**/*.css
            - /**/*.png
            - /**/*.ico
            - /webjars/**
            - /actuator/**
            - /druid/**
            - /&zwnj;**/common/**&zwnj;



