server:
    port: 9010
    maxHttpHeaderSize: 10240
    servlet:
        context-path: /wcProgram-request
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/sys?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: p@ssw0rd
    redis:
        host: localhost
        port: 6379
        #  password: yourpassword  # 本地redis暂无密码
    application:
        name: wChartProgram
    profiles:
        active: ${package.environment}
    servlet:
        multipart:
            maxFileSize: 512MB
            maxRequestSize: 300MB
    mvc:
        async:
            request-timeout: 60000

logging:
    level:
        root: INFO
        org.springframework: DEBUG



